### ISSUE TITLE
cashSpendThisRound is returning the value for the wrong player.

### ISSUE THREAD

**Issue by thorebear** [saul/demofile#101]
After upgrading from version 0.4.20 to 1.0.* I am receiving the wrong values for `cashSpendThisRound`. I have used both versions of the parser on the same demo (pre-danger-zone update demo) and seen that I am receiving wrong cashSpendThisRound values for all players.

I have compared the code for reading a `resourceProp` in both versions and seen that the newer version use `this.clientSlot` instead of `this.index` when looking up a `resourceProp`. When reverting this change I am receiving the correct values for `cashSpendThisRound` in the newer version.

I have not created a PR because I don't know if the computations of other resourceProps have changes in the newer version and I don't know if this change would break other `resourceProp`.

My local change is shown here:
https://github.com/thorebear/demofile/commit/f1f269d29f8a2137784bf2bc605f4ee3aaa301a9

**Comment by saul** [comment]
Fixed in v1.0.2 - thanks for the report
