### ISSUE TITLE
Is it possible to fetch the timestamps of CSGO events such as player_death ?

### ISSUE THREAD

**Issue by chipimix** [saul/demofile#103]
Hi there!
Awesome project 👍 
Is it possible to fetch the timestamps of CSGO events such as player_death ?
Thanks in advance!

**Comment by Technoblazed** [comment]
`demoFile.currentTime` will give the current amount of seconds through the demo that the event occurs

**Comment by saul** [comment]
Hi @chipimix, please let us know if that didn't answer your question
