### ISSUE TITLE
POV demos

### ISSUE THREAD

**Issue by Dmytro4** [saul/demofile#105]
is there a way to track events from POV demos?

**Comment by saul** [comment]
Hi @Dmytro4 - try using the WIP branch here: https://github.com/saul/demofile/pull/100. This is otherwise a duplicate of #72 - an issue that tracks getting the library to work for POV demos.

**Comment by Dmytro4** [comment]
![image](https://user-images.githubusercontent.com/22562710/51805504-ac142f00-2276-11e9-8274-46eb3dba4c9a.png)
with only 
`  demoFile.on('tickend', e => {console.log(demoFile.currentTime);}); `

**Comment by saul** [comment]
Do you mind attaching the demos to #72? Thanks
