### ISSUE TITLE
parser wrong of player_death

### ISSUE THREAD

**Issue by iisbigfish** [saul/demofile#111]
it lose one player_death record of first round.
and at round_end it can't print the entities of players.
the match is https://www.hltv.org/matches/2331061/nip-vs-hellraisers-iem-katowice-2019

**Comment by saul** [comment]
Can you give an example of the code you’re using, and the behaviour you’re expecting?

**Comment by iisbigfish** [comment]
```
  demoFile.gameEvents.on("player_death", e => {
    console.log(`Id: ${e.userid} Time: ${demoFile.currentTime}`);
   console.log(this.demoFile.entities.players, 'player')
  });

```

on first round ct kills 5 players. but the parser only show four..by the way on first round the player array is [] without any player info.
