### ISSUE TITLE
Typescript requiring definitions

### ISSUE THREAD

**Issue by Rioos** [saul/demofile#115]
Not sure how the whole TS env works but I'm importing demofile as

```
import {DemoFile} from 'demofile'
```

And it sends me a message saying that I should create a d.ts file for this.

Can't understand why this is happening, isn't the lib fully written in TS? Why is it asking me a definition tho?

Thanks sir

**Comment by saul** [comment]
You're right in thinking that the entire library is written in TypeScript, it's just that at the moment the library doesn't produce a .d.ts! I'll see if I can add this - from my preliminary testing it doesn't look like the simplest change.

**Comment by naftis** [comment]
@saul, I can also look into this. We need to add `declaration: true` to `tsconfig.json`, but it doesn't allow .js files to be compiled at the same time. But I think there must be a workaround as the `.d.ts`'s are provided for the JS files.

I started to implement the changes yesterday, but there was some problems with the project's TS compilation which needs to be looked into. I'm sure you might have already ran into this stuff.

**Comment by Rioos** [comment]
Hmmm, interesting! We might want to fully write in typescript then using `declaration: true`. Might be the easiest way to achieve that.

**Comment by naftis** [comment]
https://github.com/microsoft/TypeScript/issues/31639
TS 3.6 (release on August 13th) should allow `declaration` with `allowJs`, and then we're able to use the existing declaration files for the JS files. Alternative solution is rewriting fully with TS.

**Comment by jason-yang** [comment]
You can compile in 2 steps, 1 with `addJs: true` one with `declarations: true` (or use the cli options). You're also going to hit the very annoying problem of typescript only accepting subfolders as modules if it's in the root directory of the package... Good luck

**Comment by saul** [comment]
Released v1.1.0 with this
