### ISSUE TITLE
Demo only triggers 'start' and 'end'

### ISSUE THREAD

**Issue by tugamars** [saul/demofile#117]
Hello, this demo is only triggering the demo start and demo end events, no other events in the middle. Althought it runs good on CSGO Demo Manager.

Any ideia what is the problem, because it doesnt seem to be with the demo but also, from what i see, there are no demoFile related errors or any errors at all, it just jumps from one part to the other without going throught the middle events.

Demo: https://defs.pt/demo_download.php?id=10961

**Comment by potatoTVnet** [comment]
The demo seems to be fine, I guess the error lies in the code...
Just a few hours ago I had a similar issue with my code:
make sure that you use the following syntax for listening to game events:
`demoFile.gameEvents.on('round_start', () => { //... })`

I forgot the **.gameEvents** and it took me way too long to find that issue in my code...

**Comment by tugamars** [comment]
> 
> 
> The demo seems to be fine, I guess the error lies in the code...
> Just a few hours ago I had a similar issue with my code:
> make sure that you use the following syntax for listening to game events:
> `demoFile.gameEvents.on('round_start', () => { //... })`
> 
> I forgot the **.gameEvents** and it took me way too long to find that issue in my code...

I already runned more than 2500 demos throught the same script (before and after this one) and they all (with excpetion for the ones corrupted) passed the system as they were suppose to, this and another demo (both from the same team) are the only ones doing this. I will test today if it happens when the name is chanced or something

**Comment by saul** [comment]
Can't reproduce - that demo works fine for me with the bundled `dumpfile` script. Please re-open if you're still seeing issues.

**Comment by EloB** [comment]
I don't know if this is related but there is some issues regarding web/node version.

On web on 2 demos they never trigger any events except start/end but on node it works.

https://github.com/EloB/broken-demofile

**Comment by saul** [comment]
If `end` is being triggered with no other events, it's likely that there was a parsing error. Check the [`error` argument](https://saul.github.io/demofile/interfaces/_demo_.idemoendevent.html) on the `end` event.
