### ISSUE TITLE
Get name of all weapons held by a player

### ISSUE THREAD

**Issue by kanishkjain1995** [saul/demofile#118]
How can I get names of all weapons held by a player?
I have tried  `player.weapons`  ie: the following method in player.js
```
get weapons() {
        return this.getIndexedProps("m_hMyWeapons")
            .map(handle => this._demo.entities.getByHandle(handle))
            .filter(ent => (ent ? ent instanceof weapon_1.Weapon : false));
}
```

this returns some array, but I am unable to get the name of weapons. 
PS: I am new to nodejs, this is the first nodejs libray that I am working with.

**Comment by saul** [comment]
Can you give example code that you're using? You should be able to do something like:

```js
for (let weapon of player.weapons) {
    console.log('weapon:', weapon.itemName, 'class name:', weapon.className);
}
```

**Comment by kanishkjain1995** [comment]
Thanks a lot!! This works for me. I was trying to get all weapons using the following code:
```console.log('%j', util.inspect(attacker.weapons));```.. I am from python background, so was expecting a dictionary like structure.
