### ISSUE TITLE
Update Protobuffers

### ISSUE THREAD

**Issue by huertasdanny** [saul/demofile#120]
Don't think the latest CSGO protobuffers are being used currently resulting in replays not being parsed correctly i.e missing player death events

**Comment by saul** [comment]
Can you give an example of a demo where you're seeing this problem? The game events are entirely separate from the protobufs. If the protobufs were out of date I'd expect to see exceptions when reading the demo.

**Comment by huertasdanny** [comment]
https://drive.google.com/open?id=143uPIDkkArXV9y3s9tgILEVk5EzOgtei
This one has no player_death events and ends (demoFile.on("end", ....)) on currentTick: 317/40433

https://drive.google.com/open?id=1GIZJsHQarWMhZjz__AQMDdcjJOZbcnT1
This one gets two player_death events and ends on currentTick: 179/19187

**Comment by huertasdanny** [comment]
Hey @saul, did you get a chance to review these files?

**Comment by saul** [comment]
I'm unable to access those files - I've requested access.

**Comment by saul** [comment]
So in both of those cases, the demos are 'in eye' demos. If you check the `error` property on the end event, you would have got:

```
Error during parsing: Error: cannot remove non-existent entity
    at Object.assertExists [as default] (C:\Code\demofile\dist\assert-exists.js:5:15)
    at Entities._removeEntity (C:\Code\demofile\dist\entities.js:316:47)
    at Entities._handlePacketEntities (C:\Code\demofile\dist\entities.js:411:26)
    at DemoFile.<anonymous> (C:\Code\demofile\dist\entities.js:97:49)
    at DemoFile.emit (events.js:210:5)
    at DemoFile._handleDemoPacket (C:\Code\demofile\dist\demo.js:172:22)
    at DemoFile._parseRecurse (C:\Code\demofile\dist\demo.js:220:26)
    at processImmediate (internal/timers.js:439:21)
```

This is another case of https://github.com/saul/demofile/issues/72

I have a PR open (https://github.com/saul/demofile/pull/100) which fixes in-eye demos, but there is a decent performance hit. I've yet to spend the time finishing it as demand is seemingly low and the effort from my end is quite high.

Please continue any discussion on the linked issue.

Thanks
