### ISSUE TITLE
How can I change the playback speed of the demo and rewind at will?

### ISSUE THREAD

**Issue by l0m-dev** [saul/demofile#125]
How would this be done?

**Comment by master117** [comment]
What do you mean playback speed? This is a tool for analysis demos, it goes from the start to the end. What would playback speed achieve? Skip ticks?

Rewinding would practically mean analysing the demo from the beginning since many events build upon each other.

**Comment by l0m-dev** [comment]
I was thinking of saving the demo data after analyzing it so you can play it afterwards.

**Comment by master117** [comment]
You can not split/save parts of a demo (with this tool). If you save all of it you get the same file as before. You can not set the playback speed/behaviour of a demo file by editing the demo.

**Comment by saul** [comment]
I think @master117's comments answer your question. This library is for programmatically analysing a demo file - there is no notion of rewind or playback speed. The demo is parsed as quickly as your CPU can process it.
