### ISSUE TITLE
Knives introduced from shattered web missing from src/entities/itemdefs.ts

### ISSUE THREAD

**Issue by billfreeman44** [saul/demofile#139]
**Describe the bug**
New knives from shattered web not indexed.  Index should have the Paracord Knife (weapon_knife_cord), Survival Knife (weapon_knife_canis), Skeleton Knife (weapon_knife_skeleton), and Nomad Knife (?). See list of knives here https://counterstrike.fandom.com/wiki/Knife

**Comment by saul** [comment]
If you can provide me with a recent demo I can regenerate them for you.

**Comment by billfreeman44** [comment]
Would a share link work? steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-Xn9Av-irWSZ-jAREu-z629Z-huxwQ

**Comment by saul** [comment]
This has now been released in v1.3.1
