### ISSUE TITLE
what should i do if i want to parse dem for Dota 2? 

### ISSUE THREAD

**Issue by evangelme** [saul/demofile#141]
what should i do if i want to parse dem form Dota 2?
https://wiki.alliedmods.net/Dota_2_Events#dota_player_kill

because the events are different how can in use this? thanks

**Comment by master117** [comment]
This library has no relation to dota 2. You can not use this to parse dota 2 demos. Here is some alternatives:

https://github.com/dotabuff/manta
https://github.com/skadistats/clarity
https://github.com/skadistats/smoke
https://github.com/AliceStats/Alice

**Comment by saul** [comment]
Sorry - this library is only for CSGO. As mentioned above there are already some fantastic DoTA2 demo parsers that I suggest you use instead.
