### ISSUE TITLE
How do I get a list of userids from players in the match

### ISSUE THREAD

**Issue by KyeNormanGill** [saul/demofile#15]
I've looked through the docs but i can't seem to find how to get userids so i can match them with names and steamids etc.

**Comment by saul** [comment]
```javascript
demo.players.map(p => p.userid) // will return all player userids
demo.entities.getByUserId(userid) // will return a player that has a specifc userid
```

**Comment by KyeNormanGill** [comment]
The players map returns `[ undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined ]`

**Comment by KyeNormanGill** [comment]
Oh nevermind. Capitol I on userId.

**Comment by saul** [comment]
Thanks - I've updated my comment for future reference

**Comment by soRailicious** [comment]
@saul what about bots in a demo file? If i read in competitive matches and fight versus a bot, cause one opponent was kicked?

**Comment by saul** [comment]
That's bizarre - I was under the impression that bots that come in to replace players have a new user ID.

What problems is this causing you?

**Comment by soRailicious** [comment]
i will prepare an example later - ok?

**Comment by soRailicious** [comment]
here is the proof of it... i found the following:

player_connect {"name":"Niles","index":10,"userid":22,"networkid":"BOT","address":""}
player_team {"userid":22,"team":2,"oldteam":0,"disconnect":false,"autoteam":false,"silent":false,"isbot":true}

that should mean that BOT Niles got the UserID 22 from UserID10 or? But why does the getByUserId dont realize this info?

**Comment by saul** [comment]
No it means a bot has joined as userid 22. The index is the entity index.

**Comment by soRailicious** [comment]
hm did you understand my prob. saul?

**Comment by saul** [comment]
I'm not entirely sure - are you saying that when the bot joins, you can't get any info about the player at user ID 22?

**Comment by soRailicious** [comment]
thats correct.

but i dont know if that is my fault or its your part... maybe you download my demo file (link above) and have a look at the given rounds.

**Comment by soRailicious** [comment]
@saul i just want to try to clearify that:

i save the kills from every player in a database... if the bot is connecting (and the real player disconnecting) i dont get the kills!

so if i killed the bot - the kill will not be saved, cause i THINK that i dont get the infos with the 
`var victim = demo.entities.getByUserId(e.userid);` u know?

cause the bot have an other ID as the player before

**Comment by saul** [comment]
I've just tried the demo for myself - `getByUserId(22)` works fine for me - I can get info for Niles no problem. I'm not sure what your bug is? New players (e.g. a bot that takes over a disconnecting player) will be given a new user ID.
