### ISSUE TITLE
Player.eyeAngles returning {0, 0} in old demos

### ISSUE THREAD

**Issue by Lohouse** [saul/demofile#153]
Player.eyeAngles returns `{pitch: 0, yaw: 0}` at all times, for all players.

```
demoFile.gameEvents.on("player_death", e => {
	let pl = demoFile.entities.getByUserId(e.userid);
	let eyeAngles = pl.eyeAngles;

	console.log(pl.name);
	console.log(eyeAngles);
	console.log("");
});
```

I tested with multiple demos, results are the same. Changing the 'weapon_fire' event to something else doesn't work either.

Some demos I tested with (demos can be downloaded from following match pages):
https://www.hltv.org/matches/2293634/ldlc-vs-fnatic-dreamhack-winter-2014
https://www.hltv.org/matches/2293892/mousesports-vs-orbit-millenium-showmatch-5
https://www.hltv.org/matches/2298971/envy-vs-fnatic-dreamhack-open-cluj-napoca-2015

**Comment by saul** [comment]
I think this is because you're analysing very old demos (e.g. 5 years old) - this library didn't even exist when those demos were recorded. The way that eye angles are encoded has likely changed since that time.

**Comment by Lohouse** [comment]
Yes, it happens with demos before 2017. I might look into getting the data for these older demos when I have some more time on my hands. Would a PR to fix this issue be welcome? Thanks for your work btw, this is a great project!

**Comment by saul** [comment]
If you were to find a solution I'd definitely welcome a fix, thanks for looking into this.

**Comment by saul** [comment]
I've just tried digging into this and I can't see any props on players that are related to their eye angles:

<details>
<pre>
{
  "DT_BaseEntity": {
    "m_flSimulationTime": 0,
    "m_nModelIndex": 116,
    "m_nRenderFX": 0,
    "m_nRenderMode": 0,
    "m_fEffects": 32,
    "m_clrRender": 4294967295,
    "m_iTeamNum": 0,
    "m_iPendingTeamNum": 0,
    "m_CollisionGroup": 5,
    "m_flElasticity": 1,
    "m_flShadowCastDistance": 0,
    "m_hOwnerEntity": {
      "value": 2097151
    },
    "m_hEffectEntity": {
      "value": 2097151
    },
    "moveparent": {
      "value": 2097151
    },
    "m_iParentAttachment": 0,
    "m_iName": "",
    "movetype": 10,
    "movecollide": 0,
    "m_iTextureFrameIndex": 0,
    "m_bSimulatedEveryTick": true,
    "m_bAnimatedEveryTick": false,
    "m_bAlternateSorting": false,
    "m_bSpotted": false,
    "m_bIsAutoaimTarget": false,
    "m_fadeMinDist": 0,
    "m_fadeMaxDist": 0,
    "m_flFadeScale": 1,
    "m_nMinCPULevel": 0,
    "m_nMaxCPULevel": 0,
    "m_nMinGPULevel": 0,
    "m_nMaxGPULevel": 0
  },
  "DT_LocalPlayerExclusive": {
    "m_nTickBase": 95665,
    "m_vecVelocity[0]": 0,
    "m_vecVelocity[1]": 0,
    "m_vecVelocity[2]": 0,
    "m_vecViewOffset[2]": 0,
    "m_vecViewOffset[0]": 0,
    "m_vecViewOffset[1]": 0,
    "m_flFriction": 1,
    "m_fOnTarget": 0,
    "m_nNextThinkTick": 0,
    "m_hLastWeapon": {
      "value": 2097151
    },
    "m_vecBaseVelocity": {
      "x": -0.0009536752259009518,
      "y": -0.0009536752259009518,
      "z": -0.0009536752259009518
    },
    "m_hConstraintEntity": {
      "value": 2097151
    },
    "m_vecConstraintCenter": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_flConstraintRadius": 0,
    "m_flConstraintWidth": 0,
    "m_flConstraintSpeedFactor": 0,
    "m_bConstraintPastRadius": false,
    "m_flDeathTime": 0,
    "m_fForceTeam": -1,
    "m_nWaterLevel": 0,
    "m_flLaggedMovementValue": 1,
    "m_hTonemapController": {
      "value": 2097151
    }
  },
  "DT_CSLocalPlayerExclusive": {
    "m_vecOrigin": {
      "x": 3008,
      "y": -168,
      "z": 0
    },
    "m_vecOrigin[2]": -80,
    "m_flStamina": 0,
    "m_iDirection": false,
    "m_iShotsFired": 0,
    "m_nNumFastDucks": 0,
    "m_bDuckOverride": false,
    "m_flVelocityModifier": 1
  },
  "DT_CSNonLocalPlayerExclusive": {
    "m_vecOrigin": {
      "x": 3008,
      "y": -168,
      "z": 0
    },
    "m_vecOrigin[2]": -80
  },
  "DT_Local": {
    "m_nDuckTimeMsecs": 0,
    "m_flFallVelocity": 0.03125023842039809,
    "m_viewPunchAngle": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_aimPunchAngle": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_aimPunchAngleVel": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_iHideHUD": 2048,
    "m_flFOVRate": 0,
    "m_bDucked": false,
    "m_bDucking": false,
    "m_bInDuckJump": false,
    "m_nDuckJumpTimeMsecs": 0,
    "m_nJumpTimeMsecs": 0,
    "m_bDrawViewmodel": true,
    "m_bWearingSuit": false,
    "m_bPoisoned": false,
    "m_flStepSize": 18,
    "m_bAllowAutoMovement": true,
    "m_skybox3d.scale": 16,
    "m_skybox3d.origin": {
      "x": 6700,
      "y": -668,
      "z": 474
    },
    "m_skybox3d.area": 1,
    "m_skybox3d.fog.enable": true,
    "m_skybox3d.fog.blend": false,
    "m_skybox3d.fog.dirPrimary": {
      "x": 1,
      "y": 0,
      "z": 0
    },
    "m_skybox3d.fog.colorPrimary": 4291878362,
    "m_skybox3d.fog.colorSecondary": 4294967295,
    "m_skybox3d.fog.start": 0,
    "m_skybox3d.fog.end": 2000,
    "m_skybox3d.fog.maxdensity": 0.22499999403953552,
    "m_skybox3d.fog.HDRColorScale": 1,
    "m_audio.localSound[0]": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_audio.localSound[1]": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_audio.localSound[2]": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_audio.localSound[3]": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_audio.localSound[4]": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_audio.localSound[5]": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_audio.localSound[6]": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_audio.localSound[7]": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_audio.soundscapeIndex": 18,
    "m_audio.localBits": 0,
    "m_audio.entIndex": 1
  },
  "DT_BasePlayer": {
    "m_fFlags": 257,
    "m_iFOV": 0,
    "m_flFOVTime": 19.2109375,
    "m_afPhysicsFlags": 8,
    "m_hVehicle": {
      "value": 2097151
    },
    "m_hUseEntity": {
      "value": 2097151
    },
    "m_hGroundEntity": {
      "value": 2097151
    },
    "m_iHealth": 0,
    "m_lifeState": 2,
    "m_iBonusProgress": 0,
    "m_iBonusChallenge": 0,
    "m_flMaxspeed": 260,
    "m_iObserverMode": 5,
    "m_bActiveCameraMan": false,
    "m_bCameraManXRay": false,
    "m_bCameraManOverview": false,
    "m_bCameraManScoreBoard": false,
    "m_uCameraManGraphs": 0,
    "m_iCoachingTeam": 0,
    "m_hObserverTarget": {
      "value": 2097151
    },
    "m_iFOVStart": 90,
    "m_iDefaultFOV": 90,
    "m_hZoomOwner": {
      "value": 2097151
    },
    "m_hViewModel": [
      {
        "value": 235723
      },
      {
        "value": 2097151
      }
    ],
    "m_szLastPlaceName": "",
    "m_vecLadderNormal": {
      "x": 0,
      "y": 0,
      "z": 1
    },
    "m_ladderSurfaceProps": 0,
    "m_ubEFNoInterpParity": 1,
    "m_hPostProcessCtrl": {
      "value": 549145
    },
    "m_hColorCorrectionCtrl": {
      "value": 1409299
    },
    "m_PlayerFog.m_hCtrl": {
      "value": 2097151
    },
    "m_vphysicsCollisionState": 0,
    "m_hViewEntity": {
      "value": 2097151
    },
    "m_bShouldDrawPlayerWhileUsingViewEntity": false
  },
  "DT_CSPlayer": {
    "m_angEyeAngles[0]": 0,
    "m_angEyeAngles[1]": 0,
    "m_iMoveState": 0,
    "m_iGunGameProgressiveWeaponIndex": 0,
    "m_flGroundAccelLinearFracLastTime": 0,
    "m_cycleLatch": 0,
    "m_iAddonBits": 0,
    "m_iPrimaryAddon": 0,
    "m_iSecondaryAddon": 0,
    "m_iThrowGrenadeCounter": 0,
    "m_bWaitForNoAttack": true,
    "m_bIsRespawningForDMBonus": false,
    "m_iPlayerState": 1,
    "m_iAccount": 800,
    "m_iStartAccount": 0,
    "m_totalHitsOnServer": 0,
    "m_bInBombZone": false,
    "m_bInBuyZone": false,
    "m_bInNoDefuseArea": false,
    "m_bKilledByTaser": false,
    "m_iClass": 0,
    "m_ArmorValue": 0,
    "m_bHasDefuser": false,
    "m_bNightVisionOn": false,
    "m_bHasNightVision": false,
    "m_bInHostageRescueZone": false,
    "m_bIsDefusing": false,
    "m_bIsGrabbingHostage": false,
    "m_bIsScoped": false,
    "m_bIsWalking": false,
    "m_bResumeZoom": false,
    "m_fImmuneToGunGameDamageTime": 4.0078125,
    "m_bGunGameImmunity": true,
    "m_bHasMovedSinceSpawn": false,
    "m_bMadeFinalGunGameProgressiveKill": false,
    "m_iNumGunGameTRKillPoints": 0,
    "m_iNumGunGameKillsWithCurrentWeapon": 0,
    "m_iNumRoundKills": 0,
    "m_fMolotovUseTime": 0,
    "m_szArmsModel": "models/weapons/t_arms_phoenix.mdl",
    "m_hCarriedHostage": {
      "value": 2097151
    },
    "m_hCarriedHostageProp": {
      "value": 2097151
    },
    "m_bIsRescuing": false,
    "m_bCanMoveDuringFreezePeriod": false,
    "m_isCurrentGunGameLeader": false,
    "m_isCurrentGunGameTeamLeader": false,
    "m_unMusicID": 0,
    "m_bHasHelmet": false,
    "m_flFlashDuration": 0,
    "m_flFlashMaxAlpha": 0,
    "m_iProgressBarDuration": 0,
    "m_flProgressBarStartTime": 1.0078125,
    "m_hRagdoll": {
      "value": 2097151
    },
    "m_unCurrentEquipmentValue": 0,
    "m_unRoundStartEquipmentValue": 0,
    "m_unFreezetimeEndEquipmentValue": 0,
    "m_bIsControllingBot": false,
    "m_bCanControlObservedBot": false,
    "m_iControlledBotEntIndex": -1,
    "m_bHud_MiniScoreHidden": false,
    "m_bHud_RadarHidden": false,
    "m_nLastKillerIndex": 0,
    "m_nLastConcurrentKilled": 0,
    "m_nDeathCamMusic": 0,
    "m_bIsLookingAtWeapon": false,
    "m_bIsHoldingLookAtWeapon": false,
    "m_iNumRoundKillsHeadshots": 0
  },
  "m_flexWeight": {
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0,
    "030": 0,
    "031": 0,
    "032": 0,
    "033": 0,
    "034": 0,
    "035": 0,
    "036": 0,
    "037": 0,
    "038": 0,
    "039": 0,
    "040": 0,
    "041": 0,
    "042": 0,
    "043": 0,
    "044": 0,
    "045": 0,
    "046": 0,
    "047": 0,
    "048": 0,
    "049": 0,
    "050": 0,
    "051": 0,
    "052": 0,
    "053": 0,
    "054": 0,
    "055": 0,
    "056": 0,
    "057": 0,
    "058": 0,
    "059": 0,
    "060": 0,
    "061": 0,
    "062": 0,
    "063": 0,
    "064": 0,
    "065": 0,
    "066": 0,
    "067": 0,
    "068": 0,
    "069": 0,
    "070": 0,
    "071": 0,
    "072": 0,
    "073": 0,
    "074": 0,
    "075": 0,
    "076": 0,
    "077": 0,
    "078": 0,
    "079": 0,
    "080": 0,
    "081": 0,
    "082": 0,
    "083": 0,
    "084": 0,
    "085": 0,
    "086": 0,
    "087": 0,
    "088": 0,
    "089": 0,
    "090": 0,
    "091": 0,
    "092": 0,
    "093": 0,
    "094": 0,
    "095": 0,
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0
  },
  "DT_BCCLocalPlayerExclusive": {
    "m_flNextAttack": 1.0078125
  },
  "m_hMyWeapons": {
    "000": {
      "value": 2097151
    },
    "001": {
      "value": 2097151
    },
    "002": {
      "value": 2097151
    },
    "003": {
      "value": 2097151
    },
    "004": {
      "value": 2097151
    },
    "005": {
      "value": 2097151
    },
    "006": {
      "value": 2097151
    },
    "007": {
      "value": 2097151
    },
    "008": {
      "value": 2097151
    },
    "009": {
      "value": 2097151
    },
    "010": {
      "value": 2097151
    },
    "011": {
      "value": 2097151
    },
    "012": {
      "value": 2097151
    },
    "013": {
      "value": 2097151
    },
    "014": {
      "value": 2097151
    },
    "015": {
      "value": 2097151
    },
    "016": {
      "value": 2097151
    },
    "017": {
      "value": 2097151
    },
    "018": {
      "value": 2097151
    },
    "019": {
      "value": 2097151
    },
    "020": {
      "value": 2097151
    },
    "021": {
      "value": 2097151
    },
    "022": {
      "value": 2097151
    },
    "023": {
      "value": 2097151
    },
    "024": {
      "value": 2097151
    },
    "025": {
      "value": 2097151
    },
    "026": {
      "value": 2097151
    },
    "027": {
      "value": 2097151
    },
    "028": {
      "value": 2097151
    },
    "029": {
      "value": 2097151
    },
    "030": {
      "value": 2097151
    },
    "031": {
      "value": 2097151
    },
    "032": {
      "value": 2097151
    },
    "033": {
      "value": 2097151
    },
    "034": {
      "value": 2097151
    },
    "035": {
      "value": 2097151
    },
    "036": {
      "value": 2097151
    },
    "037": {
      "value": 2097151
    },
    "038": {
      "value": 2097151
    },
    "039": {
      "value": 2097151
    },
    "040": {
      "value": 2097151
    },
    "041": {
      "value": 2097151
    },
    "042": {
      "value": 2097151
    },
    "043": {
      "value": 2097151
    },
    "044": {
      "value": 2097151
    },
    "045": {
      "value": 2097151
    },
    "046": {
      "value": 2097151
    },
    "047": {
      "value": 2097151
    },
    "048": {
      "value": 2097151
    },
    "049": {
      "value": 2097151
    },
    "050": {
      "value": 2097151
    },
    "051": {
      "value": 2097151
    },
    "052": {
      "value": 2097151
    },
    "053": {
      "value": 2097151
    },
    "054": {
      "value": 2097151
    },
    "055": {
      "value": 2097151
    },
    "056": {
      "value": 2097151
    },
    "057": {
      "value": 2097151
    },
    "058": {
      "value": 2097151
    },
    "059": {
      "value": 2097151
    },
    "060": {
      "value": 2097151
    },
    "061": {
      "value": 2097151
    },
    "062": {
      "value": 2097151
    },
    "063": {
      "value": 2097151
    }
  },
  "DT_PlayerState": {
    "deadflag": true
  },
  "m_iAmmo": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0,
    "030": 0,
    "031": 0
  },
  "m_chAreaBits": {
    "000": 252,
    "001": 255,
    "002": 255,
    "003": 255,
    "004": 7,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0,
    "030": 0,
    "031": 0
  },
  "m_chAreaPortalBits": {
    "000": 254,
    "001": 255,
    "002": 255,
    "003": 255,
    "004": 255,
    "005": 127,
    "006": 127,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0
  },
  "m_bSpottedByMask": {
    "001": 0,
    "000": 0
  },
  "m_flEncodedController": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0
  },
  "DT_CollisionProperty": {
    "m_vecMaxs": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_nSurroundType": 0,
    "m_triggerBloat": 0,
    "m_vecSpecifiedSurroundingMins": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_nSolidType": 2,
    "m_usSolidFlags": 20,
    "m_vecSpecifiedSurroundingMaxs": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_vecMins": {
      "x": 0,
      "y": 0,
      "z": 0
    }
  },
  "m_bPlayerDominated": {
    "000": false,
    "001": false,
    "002": false,
    "003": false,
    "004": false,
    "005": false,
    "006": false,
    "007": false,
    "008": false,
    "009": false,
    "010": false,
    "011": false,
    "012": false,
    "013": false,
    "014": false,
    "015": false,
    "016": false,
    "017": false,
    "018": false,
    "019": false,
    "020": false,
    "021": false,
    "022": false,
    "023": false,
    "024": false,
    "025": false,
    "026": false,
    "027": false,
    "028": false,
    "029": false,
    "030": false,
    "031": false,
    "032": false,
    "033": false,
    "034": false,
    "035": false,
    "036": false,
    "037": false,
    "038": false,
    "039": false,
    "040": false,
    "041": false,
    "042": false,
    "043": false,
    "044": false,
    "045": false,
    "046": false,
    "047": false,
    "048": false,
    "049": false,
    "050": false,
    "051": false,
    "052": false,
    "053": false,
    "054": false,
    "055": false,
    "056": false,
    "057": false,
    "058": false,
    "059": false,
    "060": false,
    "061": false,
    "062": false,
    "063": false,
    "064": false
  },
  "m_bPlayerDominatingMe": {
    "000": false,
    "001": false,
    "002": false,
    "003": false,
    "004": false,
    "005": false,
    "006": false,
    "007": false,
    "008": false,
    "009": false,
    "010": false,
    "011": false,
    "012": false,
    "013": false,
    "014": false,
    "015": false,
    "016": false,
    "017": false,
    "018": false,
    "019": false,
    "020": false,
    "021": false,
    "022": false,
    "023": false,
    "024": false,
    "025": false,
    "026": false,
    "027": false,
    "028": false,
    "029": false,
    "030": false,
    "031": false,
    "032": false,
    "033": false,
    "034": false,
    "035": false,
    "036": false,
    "037": false,
    "038": false,
    "039": false,
    "040": false,
    "041": false,
    "042": false,
    "043": false,
    "044": false,
    "045": false,
    "046": false,
    "047": false,
    "048": false,
    "049": false,
    "050": false,
    "051": false,
    "052": false,
    "053": false,
    "054": false,
    "055": false,
    "056": false,
    "057": false,
    "058": false,
    "059": false,
    "060": false,
    "061": false,
    "062": false,
    "063": false,
    "064": false
  },
  "m_iWeaponPurchasesThisRound": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0,
    "030": 0,
    "031": 0,
    "032": 0,
    "033": 0,
    "034": 0,
    "035": 0,
    "036": 0,
    "037": 0,
    "038": 0,
    "039": 0,
    "040": 0,
    "041": 0,
    "042": 0,
    "043": 0,
    "044": 0,
    "045": 0,
    "046": 0,
    "047": 0,
    "048": 0,
    "049": 0,
    "050": 0,
    "051": 0,
    "052": 0,
    "053": 0,
    "054": 0,
    "055": 0,
    "056": 0,
    "057": 0,
    "058": 0,
    "059": 0,
    "060": 0,
    "061": 0,
    "062": 0,
    "063": 0
  },
  "m_rank": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0
  },
  "DT_BaseAnimating": {
    "m_nForceBone": 0,
    "m_vecForce": {
      "x": 0,
      "y": 0,
      "z": 0
    },
    "m_nSkin": 0,
    "m_nBody": 0,
    "m_nHitboxSet": 0,
    "m_flModelScale": 1,
    "m_bClientSideAnimation": true,
    "m_bClientSideFrameReset": false,
    "m_bClientSideRagdoll": false,
    "m_hLightingOrigin": {
      "value": 2097151
    },
    "m_flFrozen": 0,
    "m_ScaleType": 0,
    "m_bSuppressAnimSounds": false
  },
  "DT_BaseFlex": {
    "m_blinktoggle": false,
    "m_viewtarget": {
      "x": 0,
      "y": 0,
      "z": 0
    }
  },
  "DT_BaseCombatCharacter": {
    "m_LastHitGroup": 0,
    "m_hActiveWeapon": {
      "value": 2097151
    },
    "m_flTimeOfLastInjury": 0,
    "m_nRelativeDirectionOfLastInjury": 0
  },
  "m_iMatchStats_LiveTime": {
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0,
    "000": 0
  },
  "m_iMatchStats_Deaths": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  },
  "m_iMatchStats_Assists": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  },
  "m_iMatchStats_HeadShotKills": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  },
  "m_iMatchStats_Objective": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  },
  "m_iMatchStats_CashEarned": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  },
  "m_iMatchStats_Kills": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  },
  "m_iMatchStats_Damage": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  },
  "m_iMatchStats_EquipmentValue": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  },
  "m_iMatchStats_MoneySaved": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  },
  "m_iMatchStats_KillReward": {
    "000": 0,
    "001": 0,
    "002": 0,
    "003": 0,
    "004": 0,
    "005": 0,
    "006": 0,
    "007": 0,
    "008": 0,
    "009": 0,
    "010": 0,
    "011": 0,
    "012": 0,
    "013": 0,
    "014": 0,
    "015": 0,
    "016": 0,
    "017": 0,
    "018": 0,
    "019": 0,
    "020": 0,
    "021": 0,
    "022": 0,
    "023": 0,
    "024": 0,
    "025": 0,
    "026": 0,
    "027": 0,
    "028": 0,
    "029": 0
  }
}
</pre>
</details>

I'm going to close this off as 'wontfix'.
