### ISSUE TITLE
[Question] Is there a reason tickend should be emitted in the catch clause?

### ISSUE THREAD

**Issue by thecatontheflat** [saul/demofile#156]
Hey @saul 
I am referring to this line:
https://github.com/saul/demofile/blob/master/src/demo.ts#L627

This logic makes it difficult to catch errors in case the file is invalid.

**Comment by thecatontheflat** [comment]
Should we maybe add `this.emit("error", e);` to the mentioned place, so that it complies with the EventEmitter error handling recommendations (and would also give developers some flexibility as to how to handle the error): https://nodejs.org/api/events.html#events_error_events

The problem now is that if a listener on `tickend` throws an error — it'll still get executed because of the `this.emit("tickend", this.currentTick);` in the catch block.

**Comment by saul** [comment]
Agreed - fixed in 1.5.0
