### ISSUE TITLE
[Question] "ugc_map_id" not present in some demos. Is it possible to get this information elsewhere?

### ISSUE THREAD

**Issue by thecatontheflat** [saul/demofile#158]
I realize this question may not be related to the parser library, but maybe you know the answer and whoever lands at this page would benefit from the answer. :)

I noticed that `CSVCMsg_ServerInfo` message only includes `ugc_map_id` property on the custom workshop maps, but does not on the "official" maps. I am looking for a way to download the official map file based on the demofile. The game client is somehow able to figure it out, so I assumed that there must be some information available in the demofile itself that makes it possible. My further assumption was that the game client takes the `ugc_map_id` and gets the map from the Steam Workshop, but it doesn't seem to be true for the official maps since this property is empty.

Do you know how the game client knows where to download the map files?

**Comment by saul** [comment]
IIRC the map name is in the demo header itself

**Comment by thecatontheflat** [comment]
Yup! I was hoping you know how the game client knows where to download the bsp from in case it's missing (I totally understand this is out of the scope of the library). That is, in case if it's a workshop map, the game client probably does a lookup by the filename in the local files, doesn't find anything, then downloads the missing map from the Steam Workshop based on the `ugc_map_id` However, if it's an official map that is missing (say, `de_inferno`), it's not clear how does it know where to get it from, since `ugc_map_id` is empty.

**Comment by saul** [comment]
If it’s an official map that’s missing, then surely the game files are corrupt? I don’t think there’s a mechanism for this. If it’s a non-workshop map which is missing (e.g. just some custom map), then it will be downloaded from `sv_downloadurl` (which I believe is available in convars)

**Comment by saul** [comment]
See my most recent comment in this issue for more information: https://github.com/saul/demofile/issues/162
