### ISSUE TITLE
total kills for a target

### ISSUE THREAD

**Issue by pelasta** [saul/demofile#159]
Hello,

can I have an example on how to print the total kills + deaths for a certain player in the demo.

Thanks,

**Comment by thecatontheflat** [comment]
Have you seen this? https://github.com/saul/demofile/blob/master/dist/examples/dumpfile.js#L91-L108

**Comment by Borlax2** [comment]
https://i.imgur.com/4Sv63uF.png

it's printing all kills in the match, what I'm looking for is a simple code for a certain steamid64

need just the total deaths + kills for one player only -help-

**Comment by Borlax2** [comment]
Anyone can help me? need a code to print the total kills/deaths for a certain player..

**Comment by master117** [comment]
Use the code linked and add an if check on the e.attacker or e.userid against the steamid you are looking for. Store deaths and kills in variables.

**Comment by saul** [comment]
@Borlax2 full example here:

```ts
    const demoFile = new demo.DemoFile();

    demoFile.on("end", e => {
      if (e.error) {
        console.error("Error during parsing:", e.error);
      }

      const player = demoFile.players.find(x => x.steamId === "STEAM_1:0:56382797")!;
      console.log(`Player ${player.name} (${player.steamId}) scored ${player.kills}-${player.deaths}`);
    });

    // Start parsing the buffer now that we've added our event listeners
    demoFile.parse(buffer);
```

**Comment by Borlax2** [comment]
TypeError: Cannot read property 'name' of undefined

error in this line:
      console.log(`Player ${player.name} (${player.steamId}) scored ${player.kills}-${player.deaths}`);


what I'm missing?

**Comment by saul** [comment]
That means the player it can't find a player with that steam ID. Can you post the full source code?

It's also possible that that player has disconnected before the time that the demo finished.

**Comment by Borlax2** [comment]
const fs = require('fs');
const demofile = require('demofile');
const ansiStyles = require("ansi-styles");

const colourReplacements = [
  { pattern: /\x01/g, ansi: ansiStyles.whiteBright.open },
  { pattern: /\x02/g, ansi: ansiStyles.red.open },
  { pattern: /\x03/g, ansi: ansiStyles.magenta.open },
  { pattern: /\x04/g, ansi: ansiStyles.greenBright.open },
  { pattern: /\x05/g, ansi: ansiStyles.green.open },
  { pattern: /\x06/g, ansi: ansiStyles.greenBright.open },
  { pattern: /\x07/g, ansi: ansiStyles.redBright.open },
  { pattern: /\x08/g, ansi: ansiStyles.gray.open },
  { pattern: /\x09/g, ansi: ansiStyles.yellowBright.open },
  { pattern: /\x0A/g, ansi: ansiStyles.white.open },
  { pattern: /\x0B/g, ansi: ansiStyles.blueBright.open },
  { pattern: /\x0C/g, ansi: ansiStyles.blue.open },
  { pattern: /\x0D/g, ansi: ansiStyles.magenta.open },
  { pattern: /\x0E/g, ansi: ansiStyles.magentaBright.open },
  { pattern: /\x0F/g, ansi: ansiStyles.red.open },
  { pattern: /\x10/g, ansi: ansiStyles.yellow.open } // Orange
];

fs.readFile("test.dem", (err, buffer) => {
  const demoFile = new demofile.DemoFile();

  demoFile.gameEvents.on("player_death", e => {
    const victim = demoFile.entities.getByUserId(e.userid);
    const victimColour = teamNumberToAnsi(
      victim ? victim.teamNumber : 1 
    );
    const victimName = victim ? victim.name : "unnamed";
    const attacker = demoFile.entities.getByUserId(e.attacker);

    console.log(e.attacker)
        console.log(demoFile.players)
    const attackerColour = teamNumberToAnsi(
      attacker ? attacker.teamNumber : 1 
    );
    const attackerName = attacker ? attacker.name : "unnamed";
    const headshotText = e.headshot ? " HS" : "";
    console.log(
      `${attackerColour}${attackerName}${ansiStyles.reset.open} [${
        e.weapon
      }${headshotText}] ${victimColour}${victimName}${ansiStyles.reset.open}`
    );
  });

  demoFile.on("end", e => {
    if (e.error) {
      console.error("Error during parsing:", e.error);
    }
    const player = demoFile.players.find(e => e.steamId === "STEAM_0:0:84688126");
    console.log(`Player ${player.name} (${player.steamId}) scored ${player.kills}-${player.deaths}`);
  });

  function teamNumberToAnsi(teamNum) {
    if (teamNum === 2 /* Terrorists */) {
      return ansiStyles.redBright.open;
    }
    if (teamNum === 3 /* CounterTerrorists */) {
      return ansiStyles.blueBright.open;
    }
    return ansiStyles.gray.open;
  }
  demoFile.parse(buffer);
});

**Comment by saul** [comment]
OK the code seems okay - in which case I think either the player disconnected before the demo finished, or that player was never in the game.

**Comment by Borlax2** [comment]
tried to log all players in the same demo, also tried to log "demoFile.players" and it didn't print any steam_ids

**Comment by Borlax2** [comment]
the demo I'm using was downloaded from an Overwatch case. don't know if that would help.

**Comment by saul** [comment]
I believe overwatch cases have steam IDs stripped from them to hide the identity of those involved with the match.

**Comment by Borlax2** [comment]
make sense now, thanks a lot for your time.
