### ISSUE TITLE
CUserCmd parsing

### ISSUE THREAD

**Issue by yayocoNN** [saul/demofile#164]
Hello guys,

is there any chance parsing of CUserCmd will be supported soon?
How can I get the CUserCmd struct with parsing the protocol / bytes?

`struct CUserCmd {
    int pad;
    int command_number;
    int tick_count;
    vec3_t viewangles;
    vec3_t aimdirection;
    float forwardmove;
    float sidemove;
    float upmove;
    int buttons;
    char impulse;
    int weaponselect;
    int weaponsubtype;
    int randomseed;
    short mousedx;
    short mousedy;
    bool hasbeenpredicted;
};`

Any help would be appreciated!

**Comment by saul** [comment]
At the minute user commands aren't exposed: https://github.com/saul/demofile/blob/master/src/demo.ts#L555-L558

Even if support was added, unfortunately demos recorded on the client aren't supported yet anyway (see https://github.com/saul/demofile/issues/72)

**Comment by saul** [comment]
PR to implement this: https://github.com/saul/demofile/pull/201

**Comment by saul** [comment]
This is now available in v2.0.0-beta.3
