### ISSUE TITLE
Crosshair information

### ISSUE THREAD

**Issue by Elfern123** [saul/demofile#187]
Hello,

is it possible to get all crosshair information from demo and if so, how can I do it? Didn't find any relevant info from docs.

Thanks in advance

**Comment by saul** [comment]
What do you mean by crosshair information in this context?

**Comment by Elfern123** [comment]
Things like crosshair color, gap, size, alpha, outlines, dot etc. So it could be possible to get the crosshair of the player in practice. I  know this information is in the demo files somewhere.

**Comment by saul** [comment]
Raised a PR to do this: https://github.com/saul/demofile/pull/188

**Comment by saul** [comment]
Released as v1.8.0
