### ISSUE TITLE
Is it possible to check if players are in the party?

### ISSUE THREAD

**Issue by thecatontheflat** [saul/demofile#196]
Referring to the update of `2020.08.17`:

> End of match scoreboard will now display which players were playing as a party when skill groups are revealed.

https://blog.counter-strike.net/index.php/2020/08/31374/

**Comment by BlackYuzia** [comment]
I think yes, because I saw what on few sites (what **anal**yse demos of games) display party (max party per team - 2)

**Comment by saul** [comment]
Yes it should be possible. I think the data is available in the party IDs field of `CMsgGCCStrike15_v2_MatchmakingGC2ServerReserve`. I'm struggling to regenerate the latest protobufs into JS/.d.ts files, so it may take some time until I can give you some example code.

Do you have the link to a demo that exhibits this functionality?

**Comment by BlackYuzia** [comment]
@saul https://convars.com/csgostats/ru/CSGO-zxmZw-pipP5-fMik2-B2fTm-XEKLH

Try this. I hope demo do not expire.

![image](https://user-images.githubusercontent.com/25010528/104109987-febc4980-52db-11eb-8cbb-1b54a4a96ee4.png)
[Open Demo](steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-zxmZw-pipP5-fMik2-B2fTm-XEKLH)

**Comment by saul** [comment]
I've just played that demo to the end in game and it didn't show me who was in which party. Also the `ServerRankRevealAll` usermessage isn't recorded in that demo.

**Comment by BlackYuzia** [comment]
wow, that weird. Should I send any else demo or you try ask another guy?
For example @thecatontheflat

**Comment by saul** [comment]
If you watch the demo in-game do you see which players were part of which party?

**Comment by BlackYuzia** [comment]
How I remember I saw on the end of the match parties of match. But I didn't check this on demo.

**Comment by saul** [comment]
OK if somebody could find me a demo that exhibits this feature I can test my code again.

**Comment by thecatontheflat** [comment]
I couldn't see it in the game client in any of the recent matches, I wonder if they have actually implemented it yet.

**Comment by saul** [comment]
I've done some more digging and it is possible to get this information, but only via share codes. 

You can use Steam Boiler to get the `CMsgGCCStrike15_v2_MatchList` from Steam Game Coordinator for a given share code: https://github.com/akiver/boiler-writter

The party ID information is then available via: `CMsgGCCStrike15_v2_MatchList.matches[].roundstatsall[].reservation.party_ids[]`

This is outside of the scope of this library, so will close. Hope that helps.

**Comment by thecatontheflat** [comment]
Yup, that's what I thought as well, but that prop seems to be always empty. Either way, thanks for the help and for pointing me in the right direction!

**Comment by saul** [comment]
It may only be available in the last element of `roundstatsall` - have you tried looking there?

**Comment by thecatontheflat** [comment]
Yeah. Maybe it has something to do with the library I'm using for parsing the response: https://github.com/joshuaferrara/node-csgo

I'll try other libraries. Will let you know!
