### ISSUE TITLE
Add basic API methods to README

### ISSUE THREAD

**Issue by pedrofornaza** [saul/demofile#27]
I think it can be helpful to new comers and even for who already uses the project. Sometimes, getting to the docs folder can be expensive and having a quickview at the README is nice, more when you are on your phone or just in a hurry.

It dont need to be extensive or even provide ALL methods, but the main ones. Maybe something like this:

```
// Player entity
player.health // int
player.name // string
player.kills // int
player.isDefusing // bool
```

**Comment by saul** [comment]
I've added some more examples and linked to the various classes that are available.
