### ISSUE TITLE
Getting weapon name and info

### ISSUE THREAD

**Issue by pedrofornaza** [saul/demofile#28]
Since `player.weapon` returns a `BaseEntity`, how to get that weapon name (i didnt found it on the entity props)? Could we consider making a class to Weapon (like Player, Team, etc.) ?

**Comment by saul** [comment]
Yeah that sounds great. Some properties for DT_ScriptableItem (I can't remember its exact name) would be really useful too.

**Comment by pedrofornaza** [comment]
Im new to this. Does we have some docs about the demo data, how its structured, the kind of data available, etc?

**Comment by saul** [comment]
@pedrofornaza see https://gist.github.com/saul/766b8f8da1059e1ac1553cd708db6338

**Comment by pedrofornaza** [comment]
Thanks @saul, this helped a lot.

Apparently we can identify weapons based on m_iItemDefinitionIndex of DT_ScriptCreatedItem (as you mentioned, but i didnt understood at first).

Souce: https://www.unknowncheats.me/forum/counterstrike-global-offensive/129347-csgo-weapon-ids-demystified.html (dont know if they are using for the same purpose as we, but ... hahaha)
