### ISSUE TITLE
Demo currentTime scale

### ISSUE THREAD

**Issue by pedrofornaza** [saul/demofile#31]
As the docblock says `@returns {float} Number of seconds elapsed`. But i did some tests and im almost sure that its miliseconds. Which one is right?

**Comment by pedrofornaza** [comment]
Knowing that my demos are from 64 ticks servers, did some tests changing the formula and they seen pretty accurate.

Changed from:
`this.currentTick * (this.header.playbackTicks / this.header.playbackTime)`

to:
`this.currentTick / 64`

Can you help @saul ?

**Comment by saul** [comment]
What values do you get for each formula?

**Comment by saul** [comment]
Published 0.4.9 that fixes this - thanks for the report
