### ISSUE TITLE
Documentation missing properties

### ISSUE THREAD

**Issue by SteveBox0** [saul/demofile#346]
### Research

- [X] I searched but did not find an existing issue or discussion about this bug.

### Description

The current documentation does not include all properties available in the demos. For example DT_CSPlayer m_flSimulationTime is missing.

### Code to reproduce

```ts
- m_flSimulationTime
Table: DT_CSPlayer
Field: 0
```

**Comment by SteveBox0** [comment]
Looks like just the hierarchy is missing.

- CCSPlayer
  - DT_CSPlayer
    - DT_BasePlayer
      - DT_BaseCombatCharacter
        - DT_BaseFlex
          - DT_BaseAnimatingOverlay
              - DT_BaseAnimating
                - DT_BaseEntity
                  - m_flSimulationTime

**Comment by saul** [comment]
In the demofile library there isn't a concept of a send table hierarchy. If you look at the documentation for CCSPlayer you see all of the data tables flattened into that class: https://saul.github.io/demofile/interfaces/_sendtabletypes_.ccsplayer.html

Also if you search the docs for `m_flSimulationTime` you can see that it only exists on DT_BaseEntity and DT_FuncRotating: https://saul.github.io/demofile/interfaces/_sendtabletypes_.dt_baseentity.html#m_flsimulationtime

Figuring out which table contains a given prop is mentioned in the wiki page that I wrote recently: https://github.com/saul/demofile/wiki/Entity-changes#worked-example. Does that help?
