### ISSUE TITLE
Game event buytime_ended triggers only once

### ISSUE THREAD

**Issue by dannyhanke** [saul/demofile#370]
### Research

- [X] I searched but did not find an existing issue or discussion about this bug.

### Description

Hi,

I am trying to listen to the `buytime_ended` event to calculate the correct team economy value.
It seems though that this event is triggered only once after the first round. For all further rounds it is not triggered.
I was not able to find further documentation on this event nor any other information. 

Many thanks in advance.

### Code to reproduce

```ts
import fs from 'fs';
import { DemoFile } from 'demofile';

const demofile = new DemoFile();
const stream = fs.createReadStream('demo.dem');

demofile.gameEvents.on('buytime_ended', () => {
  console.log('buytime ended');
});

demofile.parseStream(stream);
```

**Comment by dannyhanke** [comment]
Thank you @saul for checking and confirming the problem.

Unfortunately the `freezeTimeEndEquipmentValue` does not work 100% of the time, because players sometimes buy after the freeze time is over. That is the reason I was going for the `buytime_ended` event.

I will try to calculate the correct equipment in a different way then. Thanks again for checking and great work on this library 👍

**Comment by saul** [comment]
Good point! Try this instead:

```ts
let buyTimeTicks = -1;
demoFile.conVars.on("change", e => {
  if (e.name === "mp_buytime") {
    const secs = parseInt(e.value);
    buyTimeTicks = secs * demoFile.tickRate;
    console.log(`Buy time is ${secs} secs (${buyTimeTicks} ticks)`);
  }
});

let buyTimeEndTick = -1;
demoFile.on("tickend", e => {
  if (buyTimeEndTick < 0 || demoFile.currentTick < buyTimeEndTick) return;

  buyTimeEndTick = -1;

  // Buy time has ende
  let tValue = 0;
  let ctValue = 0;

  for (const player of demoFile.players) {
    if (player.teamNumber == TeamNumber.Terrorists) {
      tValue += player.currentEquipmentValue;
    } else {
      ctValue += player.currentEquipmentValue;
    }
  }

  console.log(
    `Buy time end round #${demoFile.gameRules.roundsPlayed} in ${demoFile.gameRules.phase}:`
  );
  console.log(`  - Terrorist: \$${tValue}`);
  console.log(`  - Counter-Terrorist: \$${ctValue}`);
});

demoFile.gameEvents.on("round_start", e => {
  if (buyTimeTicks >= 0) buyTimeEndTick = demoFile.currentTick + buyTimeTicks;
});
```
