### ISSUE TITLE
GOTV+ Broadcasting

### ISSUE THREAD

**Issue by BeepIsla** [saul/demofile#373]
Hey,

CSGO has a special broadcasting feature known as GOTV Broadcasting / GOTV+ (https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Broadcast). It allows clients to "join" GOTV and watch the match live over HTTP instead of actually joining a server, under the hood it is very similar to demos but still with some differences, its mainly used at majors but also sometimes by other events.

I tried a bit around myself using `parseStream` but couldn't get it to work properly. It might be out of scope but I was wondering if this could be supported by this library?

**Comment by saul** [comment]
I haven't tried this myself but judging by the documentation it should work. First `GET /sync` to get the broadcast metadata, then:

1. Pass a fake demo file header into `parseStream` (any header should suffice)
2. `GET /start` using the `signup_fragment` from the `/sync` call, pass the response to `parseStream`
3. `GET /full` using the `fragment` from the `/sync` call, pass the response to `parseStream`
4. Keep calling `GET /delta` every couple of seconds with increasing fragment numbers, pass the response to `parseStream`

Please let me know how you get on.

I could try adding this functionality to the library if people would find it useful.

**Comment by BeepIsla** [comment]
Sadly does not appear to be that simple. Creating a fake demo header did prevent it from throwing an error and crashing the script but now just nothing happens. I added some logs to `parseStream` and it never consumes any of the chunks, erroring with `RangeError: Not enough data to continue parsing. 1667851878 bytes needed` and then obviously waiting for more.

**Comment by saul** [comment]
Any chance you could post the URL so I can download the chunks and try for myself? Thanks

**Comment by BeepIsla** [comment]
I've just been using the current major one, https://tv.teo.gg/match/id/stream-a but this limits testing to when a match is live (In 2 hours). Setting up your own GOTV Broadcast would probably be better, something like https://github.com/FlowingSPDG/gotv-plus-go to get going quickly

**Comment by saul** [comment]
Thanks, I managed to download some fragments from that URL. I'm part way through reverse engineering the format - it looks like some of the superfluous stuff from demo packets has been removed (like sequence numbers, which the library skipped over anyway).

The complication comes from the fact that lengths are missing (that we read in `_readIBytes`), which will require some refactoring. Another issue is that it seems to broadcast some strange svc_PacketEntities messages:

1. Tick #629652: isDelta=false, deltaFrom=0
2. Tick #630037: isDelta=true, deltaFrom=630036

The issue lies in that the `deltaFrom` references a frame that we never received entity data for. It's quite unusual - I've never seen this in a demo file.

**Comment by saul** [comment]
Actually I think I've figured out what my issue was. The concatenation of fragments should be:

1. `/{signup_fragment}/start`
2. `/{fragment}/full`
3. `/{fragment}/delta` <-- I'd missed this
4. `/{fragment+1}/delta`
5. `/{fragment+2}/delta`
6. `/{fragment+3}/delta`
7. ..etc..

**Comment by BeepIsla** [comment]
The next map is about to start and the broadcast should already be available on the same URL, `/sync` has updated with the next map and fragment count has reset too

**Comment by saul** [comment]
Very WIP PR (I can't get `node-fetch` to work locally) that's untested but _should_ work. Let me know if you try it out: https://github.com/saul/demofile/pull/374

**Comment by BeepIsla** [comment]
I was able to get it to compile by just removing fetch and replacing it with the built-in `https` module, not optimal but good for testing. After [fixing this line (Missing second argument ` url`)](https://github.com/saul/demofile/pull/374/files#diff-431fdc37ed6df0d351c283c4ce68bab295b77cda3d4fa04a569a99f6bcbb6ccbR664) I now crash somewhere entity related: `Error: no baseline for entity 0 (class ID 0)`

**Comment by saul** [comment]
I've updated the PR with a fix - let me know if that works. I've got a test written now so have some confidence this should work for you.

**Comment by BeepIsla** [comment]
It seems to be working now, thanks for your work, bots are killing each other and its logging fine. Although your current way of fetching only supports https and errors if using http.

One more thing which isn't mentioned in the wiki is that the `/sync` JSON can optionally include a `redirect_token`. I believe all it does is append the path inside `redirect_token` to the URL. Eg: `"redirect_token": "/token/s90165782017232899t1668347392/"` = `https://tv.teo.gg/live` -> `https://tv.teo.gg/live/token/s90165782017232899t1668347392/` to avoid poisoned cache on the CDN when the match changes

**Comment by saul** [comment]
Fixed in https://github.com/saul/demofile/pull/374
