### ISSUE TITLE
demo.teams `members` property is always empty

### ISSUE THREAD

**Issue by osztenkurden** [saul/demofile#376]
### Research

- [X] I searched but did not find an existing issue or discussion about this bug.

### Description

Property `members` on teams object in demoFile.teams array is always empty array. It seems that objects in demoFile.teams are different than demoFile.players[0].team properties - both have different indexes

### Code to reproduce

```ts
const demoPath = './demo.dem';

  const demoFile = new DemoFile();

  demoFile.gameEvents.on("round_start", () => {
    console.log(demoFile.teams[0].members)
  });

  demoFile.parseStream(fs.createReadStream(demoPath));
```

**Comment by saul** [comment]
`demoFile.teams[0]` will return the 'Unassigned' team. CSGO team numbers are as follows:

- `0`: Unassigned
- `1`: Spectators
- `2`: Terrorists
- `3`: Counter-Terrorists

See the [`TeamNumber` enum docs](https://demofile.dev/enums/TeamNumber.html). Defined here: https://github.com/saul/demofile/blob/f8434da/src/entities/team.ts#L7

Hope that helps!
