### ISSUE TITLE
Where are the round_end reason numbers posted?

### ISSUE THREAD

**Issue by TheFlyingVoid** [saul/demofile#38]
I've been looking for a while and cannot seem to find the "round_end" codes for when the "round_end" game event fires. I've looked all over the alliedmods website and still cannot find it. (https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#round_end) If someone can please direct me in the right direction or maybe even adding it to the documentation.

**Comment by saul** [comment]
Here you go:

```c++
TargetBombed = 1 // Target Successfully Bombed!
// 2/3 not in use in CSGO
TerroristsEscaped = 4 // The terrorists have escaped!
CTStoppedEscape = 5 // The CTs have prevented most of the terrorists from escaping!
TerroristsStopped = 6 // Escaping terrorists have all been neutralized!
BombDefused = 7 // The bomb has been defused!
CTWin = 8 // Counter-Terrorists Win!
TerroristWin = 9 // Terrorists Win!
Draw = 10 // Round Draw!
HostagesRescued = 11 // All Hostages have been rescued!
TargetSaved = 12 // Target has been saved!
HostagesNotRescued = 13 // Hostages have not been rescued!
TerroristsNotEscaped = 14 // Terrorists have not escaped!
GameStart = 16 // Game Commencing!
// 15 not in use in CSGO
TerroristsSurrender = 17 // Terrorists Surrender
CTSurrender = 18 // CTs Surrender
TerroristsPlanted = 19 // Terrorists Planted the bomb
CTsReachedHostage = 20 // CTs Reached the hostage
```

Source: https://github.com/alliedmodders/sourcemod/blob/master/plugins/include/cstrike.inc#L51-L75

Note that the cstrike.inc codes start at 0, but in CSGO they're all incremented by 1.

Hope that helps.
