### ISSUE TITLE
ServerRankUpdate doesnt work anymore

### ISSUE THREAD

**Issue by zeus1999** [saul/demofile#381]
In my last ~10 demofiles of the last 2 days, the event: "ServerRankUpdate" doesnt fire anymore?

does anything has changed?

eg.: http://replay192.valve.net/730/003602673736739717250_1114976382.dem.bz2

**Comment by MHase** [comment]
I would like to bump this issue :)
I can't find any other way to read users' ranks. I tried the code from example and searched through every other related issue, still no luck
`ServerRankUpdate` is not firing like it used to

**Comment by MHase** [comment]
small update
I was able to access user rank using
```
player.resourceProp("m_iCompetitiveRanking")
```

as a response you will get a number indicating index of current rank
to translate number to human readable format simply use array of ranks like so

```
ranks[player.resourceProp("m_iCompetitiveRanking")]
```
```
export const ranks = [
  "Unranked / Unknown",
  "Silver I (S1)",
  "Silver II (S2)",
  "Silver III (S3)",
  "Silver IV (S4)",
  "Silver Elite (SE)",
  "Silver Elite Master (SEM)",
  "Gold Nova I (GN1)",
  "Gold Nova II (GN2)",
  "Gold Nova III (GN3)",
  "Gold Nova Master (GNM)",
  "Master Guardian I (MG1)",
  "Master Guardian II (MG2)",
  "Master Guardian Elite (MGE)",
  "Distinguished Master Guardian CSGO (DMG)",
  "Legendary Eagle (LE)",
  "Legendary Eagle Master (LEM CSGO)",
  "Supreme Master First Class (SMFC)",
  "Global Elite CSGO (GE)",
];
```

e.g.
```
2 -> Silver II (S2)
10 -> Gold Nova Master (GNM)
12 -> Master Guardian II (MG2)
```

hope it help anyone who wants to get users' ranks :)

**Comment by saul** [comment]
Closing as answered - thanks @MHase!
