### ISSUE TITLE
CS2 Demo Support

### ISSUE THREAD

**Issue by Dad-Ju** [saul/demofile#395]
### Research

- [X] I searched but did not find an existing issue or discussion about this bug.

### Description

Hello, 

at first thanks for this Wonderful Module!

I know there was not done anything in last Time, but with the Release of CS2 it looks like it isnt working anymore.

Would you mind have a look into it to see if it could be fixed easily?

Thanks alot! 

### Code to reproduce

```ts
const Demo = new DemoFile()
let players = []

/** some other stuff */
            Demo.entities.on("create", e => {
                    // We're only interested in player entities being created.
                    if (!(e.entity instanceof Player)) return
        
                    if (e.entity.steamId === "BOT" || e.entity.isHltv) return

                    if(players.includes(e.entity)) return
                    players.push(e.entity)
            })

Demo.parseStream(fs.createReadStream(demoFilePath))
```

### Affected demos

[sampledemo.zip](https://github.com/saul/demofile/files/13975974/sampledemo.zip)

**Comment by Dad-Ju** [comment]
Her is the error I get

```bash
Error: Unrecognised command: 208
```

**Comment by saul** [comment]
This package does not work with CS2 - please see https://github.com/saul/demofile/discussions/384.

Many thanks
