### ISSUE TITLE
Make a browser version

### ISSUE THREAD

**Issue by mreq** [saul/demofile#4]
mikeemoo/jsgo has one, would be really nice as it would open a lot of possible uses

Is there something hindering this, or is it just a matter of correctly configuring webpack/browserify (which I was unable to)?

**Comment by saul** [comment]
I've just taken a look at this - the `ref` module needed replacing as it depends on native modules.

I've got the changes locally but it's not the cleanest implementation, and I'd like to do some performance testing before releasing.

**Comment by saul** [comment]
Work remaining until production ready:

- [x] Migrate ref to binary-parser
- [x] Manual tests to check Browserify version is working correctly
- [ ] Add test harness to ensure no breaks between old parser and new
- [ ] Compare performance with old version
- [ ] Update documentation (parse cancel, progress event)
- [ ] Fix eslint checks

**Comment by mreq** [comment]
Nice, have a dev branch? I'd be willing to help.

**Comment by saul** [comment]
Take a look at the `browserify` branch

**Comment by saul** [comment]
Closed by #5
