### ISSUE TITLE
cs_win_panel_round funfact_player data

### ISSUE THREAD

**Issue by mavrick** [saul/demofile#50]
Hey mate,

This is more a question. ``demo.gameEvents.on('cs_win_panel_round', e => { console.log(e.funfact_player); });`` returns a short http://wiki.sourcepython.com/developing/events/csgo.html#cs-win-panel-round

Any thoughts on how I can map this back to an actual player from ``demo.stringTables.findTableByName('userinfo')`` ?

**Comment by saul** [comment]
You should be using `demo.entities.getPlayerByUserid`

**Comment by mavrick** [comment]
Hey mate,

Looks like the ``e.funfact_player`` returns the player entry index, not the ``userId``

I was able to get the player data using something like

```javascript
const getByUserIndex = (index) => {
  let userInfos = demo.stringTables.findTableByName('userinfo').entries;

  for (let i = 0; i < userInfos.length; ++i) {
    let userEntry = userInfos[i];

    if (userEntry.entry == index) {
      return userEntry.userData;
    }
  }

  return null;
}
```

Cheers for pointing me in the right direction :)

**Comment by saul** [comment]
You can probably use `demo.entities.getByIndex(e.funfact_player + 1)` to get the player entity. From there you can get the user info without having to manually iterate through the userinfo array

**Comment by mavrick** [comment]
Yes, that would be a lot cleaner. Is ``getByIndex`` available in latest branch?

**Comment by saul** [comment]
Updated my comment with the correct code
