### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by naftis** [saul/demofile#56]
The module would be easier to manage with TypeScript if there were a typings file. `@types/demofile`, or `demo.d.ts` typings definition file for the module.

**Comment by saul** [comment]
Agreed - I’m considering rewriting with TypeScript anyway, this might be a good time :)

**Comment by zoidbergwill** [comment]
I've done a bit of the typing in a repo of mine so I could use some of it with VSCode, and would be happy to help with the rewrite.

**Comment by saul** [comment]
Just seen your branch @zoidbergwill - looks like a great start.

One of the really interesting parts of moving to TypeScript is that we could have a strongly type `Entity#props`.  For example:

```typescript
class DT_BasePlayer {
    m_hVehicle: EntityHandle
    m_iHealth: number
    m_iAmmo: [number, number, number, ...]
}

class CCSPlayer {
    DT_BasePlayer: DT_BasePlayer
    DT_BaseCombatCharacter: DT_BaseCombatCharacter
}

class Entity<PropsType> {
    props: PropsType
}

class Player extends Entity<CCSPlayer> {

}
```

Would allow for strongly typed access to the props. I think this would be really neat for intellisense etc.

**Comment by naftis** [comment]
> I'm not 100% sure on how we'd do the packaging of a TypeScript lib with types stuff

The library could be written in 100% js, but just the interfaces could be provided for TypeScript for starters.
For example, see [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) and browse the types for packages.

But I do feel like porting the whole project to TS would be beneficial as well. I don't have the motivation to do this for now, as my demo parser project is not active at the moment.

**Comment by zoidbergwill** [comment]
@naftis Great idea. I'll have a go at that when I get a chance. @saul is that something you'd like to have as a separate npm package in this repo? That we could manage with something like [lerna](https://lernajs.io/)?

**Comment by saul** [comment]
I’ve made significant progress migrating the entire library over to TypeScript today. The benefits so far:

- Listening to events is strongly typed (this includes listening to network messages)
- Fixed a couple of bugs around network messages whose class names don’t match up with the typical naming convention
- Compiling with strict mode, no implicit any etc. 

I have yet to implement the strongly typed entity props as I explained above. I’ll probably leave that until last - I just want to get the thing running first.

**Comment by zoidbergwill** [comment]
Awesome, work. @saul. That's exciting.

I was looking at making a PR into DefinitelyTyped, but would way rather contribute that here. Let us know if there's anything we can help with.

**Comment by jnettome** [comment]
I'm here to help also! Good job @saul :)

**Comment by saul** [comment]
I'm down to the final few compile errors now, the vast majority of which are me trying to come up with a type signature for `BaseEntity#getProp` 😄 

![image](https://user-images.githubusercontent.com/64654/46315132-7a3ed480-c5c4-11e8-8d3b-d5d1d68db45a.png)

**Comment by saul** [comment]
Progress :)

![image](https://user-images.githubusercontent.com/64654/46440923-db99ab80-c75c-11e8-90b4-de71073ed943.png)

**Comment by jnettome** [comment]
@saul I will dive into tomorrow, I'll let u know! :)
Thanks once again!

**Comment by saul** [comment]
Glad to hear it!

________________________________
