### ISSUE TITLE
AssertionError at the end of a demo 'ineyes' I recorded

### ISSUE THREAD

**Issue by haegemonia76** [saul/demofile#72]
At the end of a demo **'ineyes'** the last event **'end'** is thrown and after that my Node stop working because of this error : 

```
AssertionError [ERR_ASSERTION]: cannot remove non-existent entity
    at Entities._removeEntity (C:\wamp64\www\esport-management\Refactor BigData\node_modules\demofile\entities.js:428:5)
    at Entities._handlePacketEntities (C:\wamp64\www\esport-management\Refactor BigData\node_modules\demofile\entities.js:506:16)
    at emitOne (events.js:116:13)
    at DemoFile.emit (events.js:211:7)
    at DemoFile._handleDemoPacket (C:\wamp64\www\esport-management\Refactor BigData\node_modules\demofile\demo.js:222:12)
    at DemoFile._parseRecurse (C:\wamp64\www\esport-management\Refactor BigData\node_modules\demofile\demo.js:321:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

I tryed to handle this error at the end of my code but it seem that doesn't do the job.

if you want the demo I tested, I can upload it for you.

the demo : [demofile](https://drive.google.com/file/d/1KJkFq9vzIH-lBzVHaL6TQdk0Q9IJep_R/view?usp=sharing)

**Comment by haegemonia76** [comment]
Sorry to ask 
Did you have the time to check the problem with this demo or not ? :)

**Comment by saul** [comment]
This demo even breaks the official demoinfogo tool - there are some really strange packets in there that are confusing the library. For example, deleting the same entity three times in a row across several ticks. I think this warrants deeper investigation - I might try speaking to a Valve dev to see if they have any thoughts.

**Comment by saul** [comment]
OK so I've got a fix for this locally - I'll get around to releasing it soon. The problem was that we (and the official tool) were ignoring the `delta_from` argument of svc_PacketEntities.

**Comment by necuk** [comment]
I am still getting the same error with both demos from this issue and https://github.com/saul/demofile/issues/86

I tried both fresh `npm install demofile` and `npm upgrade demofile`. 
Here is what `npm list demofile` command shows me (executed from installation folder)
fresh install: demofile@1.0.0-beta.1
upgraded one: demofile@0.4.20

in both case I still got that error

**Comment by saul** [comment]
@necuk the fix was not part of 1.0.0-beta.1 unfortunately. There is a big performance hit which I need to think more carefully about.

**Comment by saul** [comment]
I've pushed a WIP solution to the branch `entity-baselines`. I think it's correct.

Can you try that and let me know how you get on? I've managed to make this change without any perf hit.

**Comment by Dmytro4** [comment]
![image](https://user-images.githubusercontent.com/22562710/51806282-dec32500-2280-11e9-937a-df321a46e274.png)

[replay2701.zip](https://github.com/saul/demofile/files/2800473/replay2701.zip)

**Comment by Dmytro4** [comment]
[replay2701_2.zip](https://github.com/saul/demofile/files/2800484/replay2701_2.zip)
![image](https://user-images.githubusercontent.com/22562710/51806654-22b82900-2285-11e9-8743-97c134a03624.png)

>   demoFile.on('tickend', e => {
> 	  console.log(demoFile.currentTime);
> 	  console.log(demoFile.players.map(pp => pp.userId));
> });

**Comment by saul** [comment]
I've opened a new pull request which adds support for in-eye recorded demos: https://github.com/saul/demofile/pull/197
