### ISSUE TITLE
Improved Examples

### ISSUE THREAD

**Issue by mavrick** [saul/demofile#8]
Hey, awesome module first up!

I'm still getting my head around the documentation and what data is valuable and how it's all linked together. I see a lot of questions popping up around how can I do 'x' or how do I get 'y' data for a player etc. 

I think it would be valuable to come up with a list of popular requests and some additional ones then build some code examples.

For me I want to be able to determine if a player is "**tracing**" or essentially "**aimbotting**" using the data available in the demofile. I don't have much experience with demofiles so there is a bit of a learning curve. If you wanted to leave it open for people to learn on their own then perhaps an FAQ, with examples like: 

> "If you want to determine where a player is looking then using the ``entities.on("change")`` method and look for ``DT_CTPlayerBase->m_blah`` value".

What do you think?

**Comment by saul** [comment]
Completely agree - as it stands the library is quite low-level. In the near future (i.e. this month), I plan to add functions to the Entity class like:

- `getOrigin`
- `getOwner` (for getting the thrower of grenades)

And methods to a new Player class such as:

- `getViewAngles`
- `getSteamId`
- `getUserId`
- `getWeapons`

Watch this space :)

**Comment by saul** [comment]
@mavrick - what do you think of these provisional API additions? I've got it working locally, but wondering if there are any other functions you think would be useful:

Entity:
- getPosition
- getOwner
- getTeamNumber

Player:
- getHealth
- getEyeAngles
- getAccount
- getLifeState
- isAlive
- getUserInfo
- getUserId
- getSteamId
- getName
- isFakePlayer
- isHltv
- getArmor
- getPlaceName
- getActiveWeapon
- getWeapons
- isInBombZone
- isInBuyZone
- isDefusing
- hasDefuser
- hasHelmet
- getKills
- getAssists
- getDeaths
- hasC4

Entities:
- getByUserId

**Comment by derpalmer** [comment]
Maybe insted of getTeamNumber something like getTeam? And maybe a Team class for all that info would be great. Keep up the good work!

**Comment by saul** [comment]
That makes sense :) I've also made them getter properties instead of functions too.

**Comment by saul** [comment]
I've added:

Team:
* teamNumber
* players
* clanName
* teamName
* score
* scoreFirstHalf
* scoreSecondHalf

Anything else?

**Comment by saul** [comment]
@derpalmer I've added:

Team:
* teamNumber
* players
* clanName
* teamName
* score
* scoreFirstHalf
* scoreSecondHalf

Anything else?

**Comment by derpalmer** [comment]
Mabe add the values from m_szTeamFlagImage and m_szTeamLogoImage as well, could be useful.

**Comment by mavrick** [comment]
Hey mate,

These additional options are a great start! Using the demo files to rebuild match stats will be much easier now. 

For ``player`` what about:

- getBank

Also, I was thinking what about round information:

``round``

- getRound (int)
- isKnife (bool)
- score (object of teams with running score for this round)
- getWinner (teamId) - round winner
- bombPlanted (bool)
- bombDefused (bool)
- getRoundMVP

Some additional things I'd like for data analysis if possible, would be:

- Ability to determine if an entity is a player and if they are an ally or enemy
  - ``isAlly()``
- Entities in FOV (who/what can the player currently see on the screen during an event)
  - ``visibileEntitiesInFov()``
- All available entities within FOV
  - ``availableEntitiesInFov()``
- Ability to determine is the crosshair/eyeAngle is on an entity at a given event.
  - ```hasEntityInFocus()```

**Examples:**

```javascript
var entities = player.visibileEntitiesInFov();

for(var k in entities)
{
	var entity = entities[k];

	if(entity.isPlayer() == true && player.hasEntityInFocus(entity) == true)
	{
		console.log("player is on the screen and we're locked on");

		if(entity.isAlly(player) == true)
		{
			console.log("they are on the same team")
		}
		else
		{
			console.log("the enemy has been found");
		}
	}
}
```

or, on a kill event:

```javascript
player.on("kill", function(event, entity)
{
	if(entity.isVisible() == true)
	{
		// possible knife or gun kill
		console.log("kill was visible on screen");
	}
	else
	{
		// wall bang, grenade, molly kill
		console.log("kill was made offscreen");
		console.log(event.killType()); // what was the kill from?
	}
});
```

Then using them altogether, example:

```javascript
player.on("eyeAngles", function(event)
{
	var entities = event.availableEntities();

	for(var k in entities)
	{
		var entity = entities[k];

		if(
			entity.isPlayer() == true && 
			player.hasEntityInFocus(entity) == true && 
			entity.isVisible() == false
		)
		{
			console.log("player is aiming at someone through a wall or door");
		}
	}
});
```

I'm just writing 'freehand' for the above examples, they are in no way accurate based on current documentation. 

I'll add some more tonight when I get home.

**Comment by saul** [comment]
Thanks for the thorough feedback.

> For ``player`` what about:
> 
> - getBank

Use `player.account`.

> ``round``
>
> - getRound (int)
> - isKnife (bool)
> - score (object of teams with running score for this round)
> - getWinner (teamId) - round winner
> - bombPlanted (bool)
> - bombDefused (bool)
> - getRoundMVP

Most of this information is available in the `round_end` and `round_mvp` events, alongside `Team#score`. Unfortunately I don't think there's a way to determine if a round was a 'knife round'. 

> - Ability to determine if an entity is a player and if they are an ally or enemy
>   - ``isAlly()``

This should be do-able, just need to check whether the team numbers match or if mp_teammates_are_enemies is set.

> - Entities in FOV (who/what can the player currently see on the screen during an event)
>   - ``visibileEntitiesInFov()``
> - All available entities within FOV
>   - ``availableEntitiesInFov()``
> - Ability to determine is the crosshair/eyeAngle is on an entity at a given event.
>   - ```hasEntityInFocus()```

Unfortunately none of these will be viable (besides possibly `availableEntitiesInFov`. We need to be able to trace lines across the game world, which we can't do unless we have a full 3D representation of the level loaded into memory. This would be beyond the scope of this library.

**Comment by saul** [comment]
See e41ca9d9b73926ee0cbfe55c417d5935ac1eabae, I've added isSpotted, isSpottedBy, allSpotters, hasSpotted, allSpotted and isFriendly functions to the Player class.

**Comment by mavrick** [comment]
Awesome, based on those additions does this look correct:

```javascript
demo.entities.on('change', function() 
{
	console.dir(arguments);
});
```

```javascript
{ '0':
   { entity:
      Player {
        _demo: [Object],
        index: 10,
        classId: 35,
        serialNum: 923,
        props: [Object],
        clientSlot: 9 },
     tableName: 'm_iMatchStats_KillReward',
     varName: '003',
     oldValue: 0,
     newValue: 200 } }
```

```javascript
demo.entities.on('change', function(data) 
{
	var Entity = data.entity;
	var tableName = data.tableName;
	var varName = data.varName;

	var filters = [ 'm_bIsWalking', 'm_flLowerBodyYawTarget', 'm_bStrafing', 'm_angEyeAngles', 'm_bIsScoped' ];

	if(tableName == 'DT_CSPlayer' && filters.indexOf(varName) != -1)
	{
		var playerEntities = Entity.allSpotted;

		for(var k in playerEntities)
		{
			var playerEntity = playerEntities[k];

			if(playerEntity.isFriendly(Entity.teamNumber) == false)
			{
				console.log("we've spotted an enemy");
			}
		}
	}
});
```

Is it possible to determine distance from one entity to another?

**Comment by cinkonaap** [comment]
> Is it possible to determine distance from one entity to another?

I think each player entity has `position` property, so you can calculate distance with simple vector manipulation. 

```
magnitude = Math.sqrt(v.x^2 + v.y^2 + v.z^2)
```

It should be easier if position or euler angles properties are transformed to some `Vector` objects, for easier manipulation.

**Comment by cinkonaap** [comment]
And what about more generic information, like `current map` for example?

Is there any good external reference, what data can be extracted from `stringtables`, `gameevents` etc.?

**Comment by saul** [comment]
@cinkonaap the current map is available in DemoFile#header. I don't believe there is a reference as to what's in string tables. For events, see: https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events

**Comment by mavrick** [comment]
@cinkonaap thanks for that. I will have a crack at it.
