### ISSUE TITLE
cashSpendThisRound is broken.

### ISSUE THREAD

**Issue by thorebear** [saul/demofile#80]
After upgrading from version `0.4.15` to `0.4.19` I have started to receive `undefined` when calling `somePlayer.cashSpendThisRound`. 
I have tried different versions of this library in order to narrow down the problem, and I have found that the problem doesn't exist in version `0.4.17` but is introduced with version `0.4.18` (and still exists in version `0.4.19`).
The result of `undefined` when calling `somePlayer.cashSpentThisRound` is not consistent and in some cases, the real value is returned (but before version `0.4.18` the real value was returned all the time). 

I have looked at the changes from version `0.4.17` to `0.4.18` but I don't feel I have the right knowledge to investigate this problem any further. 

**Example:** 
- Inferno demo from: [here](https://www.hltv.org/matches/2325914/north-vs-fragsters-iem-chicago-2018-europe-closed-qualifier )
- In tick `7092`: `p.cashSpendThisRound` returns `undefined` in version `0.4.18` but `700` in version `0.4.17` where `p` is the player with userid `21`.

**Comment by saul** [comment]
Fixed in v0.4.20
