### ISSUE TITLE
Possible to get voice chat events?

### ISSUE THREAD

**Issue by Technoblazed** [saul/demofile#83]
Hi there!

Was just wondering if it's possible to parse voice chat from within demos, I've been looking around for events and couldn't seem to find any. With you having coded the parser I was wondering if it was something you've come across or attempted.

Thanks :D

**Comment by saul** [comment]
So the voice data is definitely in the demo, as the `svc_VoiceData` net message. The problem is the voice data is in a proprietary codec - the codecs for which are available in `Counter-Strike Global Offensive\bin\vaudio_*.dll`. I did spend some time a few months ago trying to reverse engineer this, I've just asked a Source engine dev if they can give me iaudiocodec.h to help me decode this.

**Comment by Technoblazed** [comment]
Thanks a bunch for looking into it :D

**Comment by Technoblazed** [comment]
Being able to get the voice data itself would also be pretty neat if that's something obtainable :o - Also thanks for the update again asher.

**Comment by saul** [comment]
@asherkin the way I was thinking of doing it was to dlopen the DLL and interact with it that way. However I don’t have an up to date voicecodec.h, at least not one from the CSGO branch :(

**Comment by l0m-dev** [comment]
Any news on this?

**Comment by saul** [comment]
Unfortunately not, I haven't looked at it since my last comment

**Comment by 2Eggsss** [comment]
Since the source engine leak happened yesterday, is it possible that any files from there might help? Not exactly sure what files are required but yea...

**Comment by saul** [comment]
Possibly - I've had a quick look but the Windows CELT library isn't bundled so I can't test further. Using `node-celt` fails with `Sampling rate must be between 32 kHz and 96 kHz` (CSGO's CELT sample rate is 22050Hz)

**Comment by EloB** [comment]
@saul Have you had time to investigate this more? I WOULD LOVE THIS FEATURE <3

**Comment by saul** [comment]
I haven't had any more time to dig into this unfortunately. Unless someone can find the exact CELT source/library that is used in the Source engine there's not much I can do.

**Comment by EloB** [comment]
> I haven't had any more time to dig into this unfortunately. Unless someone can find the exact CELT source/library that is used in the Source engine there's not much I can do.

How can we figure out that? I trying to building an app that needs somehow to export the voice from demo. My low level skills are very limited. I can gladly research if someone tells me what to look for.

**Comment by saul** [comment]
I've found a solution to this that uses `csgo/bin/linux64/vaudio_celt_client.so` from the CSGO Linux dedicated server.

First use `demofile` to extract the raw CELT-encoded audio for each player from the demo file:

```ts
import { DemoFile } from "demofile";
import * as fs from "fs";

function parseDemoFile(path: string) {
  const stream = fs.createReadStream(path);
  const demoFile = new DemoFile();

  const audioFds = new Map<number, number>();

  demoFile.on("svc_VoiceInit", data => {
    console.log("svc_VoiceInit", data);

    if (
      data.codec !== "vaudio_celt" ||
      data.quality !== 5 ||
      data.version !== 3
    ) {
      console.error("Unexpected voice codec");
      process.exit(1);
    }
  });

  demoFile.on("svc_VoiceData", msg => {
    const player = demoFile.entities.getBySteam64Id(msg.xuid);
    if (!player) return;

    let fd = audioFds.get(player.userId);
    if (!fd) {
      fd = fs.openSync(`voice-${msg.xuid}.bin`, "w");
      audioFds.set(player.userId, fd);
    }

    fs.writeSync(fd, msg.voiceData);
  });

  demoFile.on("end", e => {
    if (e.error) {
      console.error("Error during parsing:", e.error);
      process.exitCode = 1;
    }

    audioFds.forEach(fd => {
      fs.closeSync(fd);
    });

    console.log("Finished.");
  });

  // Start parsing the stream now that we've added our event listeners
  demoFile.parseStream(stream);
}

parseDemoFile(process.argv[2]!);
```

Then pass each `audio-12345.bin` file into my [node-csgo-voice](https://github.com/saul/node-csgo-voice) application. This will produce .wav files of player voice.
 
Let me know if this doesn't work for you and I'll re-open.

**Comment by akiver** [comment]
This is a really cool addition to what we can do with demos.
Thank you for sharing your knowledge @saul .
You rock 😎

**Comment by KillaBoi** [comment]
Thanks a lot for this @saul , glad to see it finally work!

**Comment by saul** [comment]
Unfortunately the codec seems specific to Steam/CSGO, I haven't been able to find the source for the CELT version that they've used. From the CELT docs:

> most new releases (even minor ones) change the bit-stream, so compatibility is not preserved

Unless somebody can find the exact CELT source that is used in CSGO, and ports it to another language, we're stuck with FFI.

**Comment by maxpain** [comment]
> Unless somebody can find the exact CELT source that is used in CSGO, and ports it to another language, we're stuck with FFI.

What about this? Is this helpful for us?
https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/engine/voice_codecs/celt/voiceencoder_celt.cpp#L181

**Comment by saul** [comment]
No, that isn't the source to the actual CELT codec.
