### ISSUE TITLE
Broken Documentation on Github Site

### ISSUE THREAD

**Issue by tjhiry29** [saul/demofile#90]
It appears the new github site has broken your documentation.

The following URL returns a 404 for me.
https://saul.github.io/demofile/classes/_entities_player_.player.html

![screenshot_2018-10-28 page not found github pages](https://user-images.githubusercontent.com/14966292/47622159-0666ed80-dad8-11e8-8d83-e96dac78409e.png)

**Comment by saul** [comment]
Thanks for the report - this has been fixed. `.nojekyll` was missing from the docs folder.
