### ISSUE TITLE
How to get grenade throw position?

### ISSUE THREAD

**Issue by tugamars** [saul/demofile#94]
Hi, first of all thanks for this fantastic library.

I have found a problem ( i think ), the event called "grenade_thrown" is never called, so there is no way of catching the position the nade/flash/smoke/etc was thrown from, right?

Is there any other event that can be used for that effect?

**Comment by clappis** [comment]
I have the same problem, only works this events:

hegrenade_detonate, flashbang_detonate and smokegrenade_detonate

**Comment by EloB** [comment]
@saul Is it possible to get `Weapon` instead of `BaseEntity?

**Comment by saul** [comment]
Grenade projectiles aren't weapons, so unfortunately not
